BEGIN;

SET search_path TO lensql;

INSERT INTO errors (id, category, subcategory, name) VALUES
(  2, '1.SYN', 'Ambiguous database object', 'Ambiguous column'),
(  3, '1.SYN', 'Ambiguous database object', 'Ambiguous function'),
(  4, '1.SYN', 'Undefined database object', 'Undefined column'),
(  5, '1.SYN', 'Undefined database object', 'Undefined function'),
(  6, '1.SYN', 'Undefined database object', 'Undefined parameter'),
(  7, '1.SYN', 'Undefined database object', 'Undefined object'),
(  8, '1.SYN', 'Undefined database object', 'Invalid schema name'),
(  9, '1.SYN', 'Undefined database object', 'Misspellings'),
( 10, '1.SYN', 'Undefined database object', 'Synonyms'),
( 11, '1.SYN', 'Undefined database object', 'Omitting quotes around character data'),
( 12, '1.SYN', 'Data type mismatch', 'Failure to specify column name twice'),
( 35, '1.SYN', 'Data type mismatch', 'IS where not applicable'),
( 13, '1.SYN', 'Data type mismatch', 'Data type mismatch'),
( 14, '1.SYN', 'Illegal aggregate function placement', 'Using aggregate function outside SELECT or HAVING'),
( 15, '1.SYN', 'Illegal aggregate function placement', 'Aggregate functions cannot be nested'),
( 16, '1.SYN', 'Illegal or insufficient grouping', 'Extraneous or omitted grouping column'),
( 17, '1.SYN', 'Illegal or insufficient grouping', 'HAVING without GROUP BY'),
( 26, '1.SYN', 'Invalid subqueries', 'Too many columns in subquery'),
(106, '1.SYN', 'Invalid subqueries', 'Missing quantifier'),
( 18, '1.SYN', 'Common syntax error', 'Confusing function with function parameter'),
( 19, '1.SYN', 'Common syntax error', 'Using WHERE twice'),
( 20, '1.SYN', 'Common syntax error', 'Omitting the FROM clause'),
( 21, '1.SYN', 'Common syntax error', 'Comparison with NULL'),
( 22, '1.SYN', 'Common syntax error', 'Omitted semicolon'),
( 38, '1.SYN', 'Common syntax error', 'Additional semicolon'),
( 23, '1.SYN', 'Common syntax error', 'Date time field overflow'),
( 24, '1.SYN', 'Common syntax error', 'Duplicate clause'),
( 25, '1.SYN', 'Common syntax error', 'Undefined correlation name'),
( 27, '1.SYN', 'Common syntax error', 'Confused table names with column names'),
( 30, '1.SYN', 'Common syntax error', 'Confused the order of keywords (e.g., FROM customer SELECT fee)'),
( 32, '1.SYN', 'Common syntax error', 'Confused the syntax of keywords (e.g., LIKE ("A," "B"))'),
( 33, '1.SYN', 'Common syntax error', 'Omitting commas'),
(107, '1.SYN', 'Common syntax error', 'Unmatched brackets'),
(108, '1.SYN', 'Common syntax error', 'Curly or square brackets'),
( 36, '1.SYN', 'Common syntax error', 'Nonstandard keywords or standard keywords in wrong context'),
( 37, '1.SYN', 'Common syntax error', 'Nonstandard operators (e.g., &&, \|\| or ==)'),
(109, '1.SYN', 'Common syntax error', 'Different tuples in set operation'),
( 40, '2.SEM', 'Inconsistent expression', 'Implied, tautological or inconsistent expression'),
( 41, '2.SEM', 'Inconsistent expression', 'DISTINCT in SUM or AVG'),
( 42, '2.SEM', 'Inconsistent expression', 'DISTINCT that might remove important duplicates'),
( 45, '2.SEM', 'Inconsistent expression', 'Mixed a >0 with IS NOT NULL or empty string with NULL'),
( 46, '2.SEM', 'Inconsistent join', 'NULL in IN/ANY/ALL subquery'),
( 47, '2.SEM', 'Inconsistent join', 'Join condition on unmatchable column'),
( 49, '2.SEM', 'Duplicate rows', 'Many duplicates'),
( 50, '2.SEM', 'Redundant column output', 'Constant column output'),
( 51, '2.SEM', 'Redundant column output', 'Duplicate column output'),
( 39, '3.LOG', 'Operator error', 'AND instead of OR'),
( 52, '3.LOG', 'Operator error', 'OR instead of AND'),
( 53, '3.LOG', 'Operator error', 'Extraneous NOT operator'),
( 54, '3.LOG', 'Operator error', 'Missing NOT operator'),
( 55, '3.LOG', 'Operator error', 'Substituting existence negation with <>'),
( 57, '3.LOG', 'Operator error', 'Incorrect comparison operator or incorrect value compared'),
( 58, '3.LOG', 'Join error', 'Incorrect table reference'),
( 62, '3.LOG', 'Join error', 'Missing table reference'),
( 59, '3.LOG', 'Join error', 'Extraneous table reference'),
( 60, '3.LOG', 'Join error', 'Join condition on incorrect column'),
( 61, '3.LOG', 'Join error', 'Join condition with incorrect comparison operator'),
( 48, '3.LOG', 'Join error', 'Missing join condition'),
(104, '3.LOG', 'Join error', 'Condition on OUTER JOIN'),
( 63, '3.LOG', 'Nesting error', 'Improper nesting of expressions'),
( 64, '3.LOG', 'Nesting error', 'Improper nesting of subqueries'),
( 65, '3.LOG', 'Expression error', 'Extraneous quotes'),
( 66, '3.LOG', 'Expression error', 'Missing expression'),
( 68, '3.LOG', 'Expression error', 'Extraneous expression'),
( 67, '3.LOG', 'Expression error', 'Expression on incorrect column'),
( 69, '3.LOG', 'Expression error', 'Expression in incorrect clause'),
( 43, '3.LOG', 'Expression error', 'Wildcards without LIKE'),
(110, '3.LOG', 'Expression error', 'Wrong wildcard'),
(111, '3.LOG', 'Expression error', 'Invalid wildcard'),
( 70, '3.LOG', 'Projection error', 'Extraneous column in SELECT'),
( 71, '3.LOG', 'Projection error', 'Missing column from SELECT'),
( 72, '3.LOG', 'Projection error', 'Missing DISTINCT from SELECT'),
( 73, '3.LOG', 'Projection error', 'Missing AS from SELECT'),
( 74, '3.LOG', 'Projection error', 'Missing column from ORDER BY clause'),
( 75, '3.LOG', 'Projection error', 'Incorrect column in ORDER BY clause'),
( 77, '3.LOG', 'Projection error', 'Incorrect ordering of rows'),
(112, '3.LOG', 'Clause error', 'Missing WHERE clause'),
(113, '3.LOG', 'Clause error', 'Missing GROUP BY clause'),
(114, '3.LOG', 'Clause error', 'Missing HAVING clause'),
(115, '3.LOG', 'Clause error', 'Missing ORDER BY clause'),
(116, '3.LOG', 'Clause error', 'Missing LIMIT clause'),
(117, '3.LOG', 'Clause error', 'Missing OFFSET clause'),
(118, '3.LOG', 'Clause error', 'Extraneous WHERE clause'),
(119, '3.LOG', 'Clause error', 'Extraneous GROUP BY clause'),
(120, '3.LOG', 'Clause error', 'Extraneous HAVING clause'),
( 76, '3.LOG', 'Clause error', 'Extraneous ORDER BY clause'),
(121, '3.LOG', 'Clause error', 'Extraneous LIMIT clause'),
(122, '3.LOG', 'Clause error', 'Extraneous OFFSET clause'),
(123, '3.LOG', 'Clause error', 'Incorrect LIMIT'),
(124, '3.LOG', 'Clause error', 'Incorrect OFFSET'),
( 80, '3.LOG', 'Function error', 'Incorrect function'),
( 78, '3.LOG', 'Function error', 'DISTINCT as function parameter where not applicable'),
( 79, '3.LOG', 'Function error', 'Missing DISTINCT from function parameter'),
( 81, '3.LOG', 'Function error', 'Incorrect column as function parameter'),
( 82, '4.COM', 'Complication', 'Unnecessary complication'),
( 83, '4.COM', 'Complication', 'Unnecessary DISTINCT in SELECT clause'),
( 84, '4.COM', 'Complication', 'Unnecessary table reference'),
( 85, '4.COM', 'Complication', 'Unused correlation name'),
( 86, '4.COM', 'Complication', 'Tables have the same data'),
(125, '4.COM', 'Complication', 'Correlation name identical to table name'),
( 87, '4.COM', 'Complication', 'Unnecessarily general comparison operator'),
( 88, '4.COM', 'Complication', 'LIKE without wildcards'),
( 89, '4.COM', 'Complication', 'Unnecessarily complicated SELECT in EXISTS subquery'),
( 90, '4.COM', 'Complication', 'IN/EXISTS can be replaced by comparison'),
( 91, '4.COM', 'Complication', 'Unnecessary aggregate function'),
( 92, '4.COM', 'Complication', 'Unnecessary DISTINCT in aggregate function'),
( 93, '4.COM', 'Complication', 'Unnecessary argument of COUNT'),
( 94, '4.COM', 'Complication', 'Unnecessary GROUP BY in EXISTS subquery'),
( 95, '4.COM', 'Complication', 'GROUP BY with singleton groups'),
( 96, '4.COM', 'Complication', 'GROUP BY with only a single group'),
( 97, '4.COM', 'Complication', 'GROUP BY can be replaced with DISTINCT'),
( 98, '4.COM', 'Complication', 'UNION can be replaced by OR'),
( 99, '4.COM', 'Complication', 'Unnecessary column in ORDER BY clause'),
(100, '4.COM', 'Complication', 'ORDER BY in subquery'),
(101, '4.COM', 'Complication', 'Inefficient HAVING'),
(102, '4.COM', 'Complication', 'Inefficient UNION'),
(103, '4.COM', 'Complication', 'Condition in the subquery can be moved up'),
(105, '4.COM', 'Complication', 'OUTER JOIN can be replaced by INNER JOIN'),
(126, '4.COM', 'Complication', 'Unused CTE'),
(  1, 'x.DEP', 'Deprecated', 'Omitting correlation names'),
( 28, 'x.DEP', 'Deprecated', 'Restriction in SELECT clause'),
( 29, 'x.DEP', 'Deprecated', 'Projection in WHERE clause'),
( 31, 'x.DEP', 'Deprecated', 'Confusing the logic of keywords'),
( 34, 'x.DEP', 'Deprecated', 'Curly, square or unmatched brackets'),
( 44, 'x.DEP', 'Deprecated', 'Incorrect wildcard'),
( 56, 'x.DEP', 'Deprecated', 'Putting NOT in front of incorrect IN/EXISTS');

COMMIT;