services:
  nginx:
    build: .
    image: davideponzini/lensql:nginx
    container_name: lensql_nginx
    restart: unless-stopped
    ports:
      - "3001:80"

  server:
    build: ./server
    image: davideponzini/lensql:server
    container_name: lensql_server
    restart: unless-stopped
    depends_on:
      - db_admin
      - db_users
    environment:
      - DB_HOST=db_admin
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=postgres
      - USER_DB_HOST=db_users
      - USER_DB_PORT=5432
      - MAX_CONNECTION_HOURS=4
      - CLEANUP_INTERVAL_SECONDS=3600
      - MAX_CONTENT_LENGTH=20971520
    env_file:
      - server/.env

  db_admin:
    build: ./db_admin
    image: davideponzini/lensql:db_admin
    container_name: lensql_db_admin
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - lensql_pgdata:/var/lib/postgresql/data

  db_users:
    image: postgres:latest
    command: -c 'max_connections=500'
    container_name: lensql_db_users
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - lensql_pgdata_users:/var/lib/postgresql/data

volumes:
  lensql_pgdata:
  lensql_pgdata_users:
