services:
  lensql:
    image: davideponzini/lensql:1
    ports:
      - "8888:8888"
    container_name: lensql_client
    depends_on:
      - db
    environment:
      LENSQL_HOST: https://ponzidav.com/lensql
      LENSQL_DB_HOST: db
      LENSQL_DB_PORT: 5432
      LENSQL_DB_USERNAME: postgres
      LENSQL_DB_PASSWORD: password
      LENSQL_DB_NAME: postgres
    volumes:
      - lensql_client_data:/home/user

  db:
    image: postgres:latest
    container_name: lensql_client_db
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - lensql_client_pgdata:/var/lib/postgresql/data

volumes:
  lensql_client_data:
  lensql_client_pgdata:
