BEGIN;

DROP SCHEMA IF EXISTS lensql CASCADE;
CREATE SCHEMA lensql;

GRANT USAGE ON SCHEMA lensql TO lensql;
ALTER DEFAULT PRIVILEGES IN SCHEMA lensql GRANT ALL ON TABLES TO lensql;
ALTER DEFAULT PRIVILEGES IN SCHEMA lensql GRANT ALL ON SEQUENCES TO lensql;

CREATE TABLE lensql.users (
    username VARCHAR(255) PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE lensql.queries (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL REFERENCES lensql.users(username),
    query TEXT NOT NULL,
    success BOOLEAN NOT NULL,
    ts TIMESTAMP NOT NULL DEFAULT NOW()
);


CREATE TABLE lensql.buttons (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL REFERENCES lensql.users(username),
    query_id INTEGER REFERENCES lensql.queries(id),
    button VARCHAR(255) NOT NULL,
    data TEXT DEFAULT NULL,
    chat_id INTEGER NOT NULL,
    msg_id INTEGER NOT NULL,
    ts TIMESTAMP NOT NULL DEFAULT NOW()
);

COMMIT;