BEGIN;

SET search_path TO lensql;

INSERT INTO errors(id, category, subcategory, error) VALUES
    (  1, 'SYN', 'Ambiguous database object', 'Omitting correlation names'),
    (  2, 'SYN', 'Ambiguous database object', 'Ambiguous column'),
    (  3, 'SYN', 'Ambiguous database object', 'Ambiguous function'),
    (  4, 'SYN', 'Undefined database object', 'Undefined column'),
    (  5, 'SYN', 'Undefined database object', 'Undefined function'),
    (  6, 'SYN', 'Undefined database object', 'Undefined parameter'),
    (  7, 'SYN', 'Undefined database object', 'Undefined object'),
    (  8, 'SYN', 'Undefined database object', 'Invalid schema name'),
    (  9, 'SYN', 'Undefined database object', 'Misspellings'),
    ( 10, 'SYN', 'Undefined database object', 'Synonyms'),
    ( 11, 'SYN', 'Undefined database object', 'Omitting quotes around character data'),
    ( 12, 'SYN', 'Data type mismatch', 'Failure to specify column name twice'),
    ( 13, 'SYN', 'Data type mismatch', 'Data type mismatch'),
    ( 14, 'SYN', 'Illegal aggregate function placement', 'Using aggregate function outside SELECT or HAVING'),
    ( 15, 'SYN', 'Illegal aggregate function placement', 'Grouping error: aggregate functions cannot be nested'),
    ( 16, 'SYN', 'Illegal or insufficient grouping', 'Grouping error: extraneous or omitted grouping column'),
    ( 17, 'SYN', 'Illegal or insufficient grouping', 'Strange HAVING: HAVING without GROUP BY'),
    ( 18, 'SYN', 'Common syntax error', 'Confusing function with function parameter'),
    ( 19, 'SYN', 'Common syntax error', 'Using WHERE twice'),
    ( 20, 'SYN', 'Common syntax error', 'Omitting the FROM clause'),
    ( 21, 'SYN', 'Common syntax error', 'Comparison with NULL'),
    ( 22, 'SYN', 'Common syntax error', 'Omitting the semicolon'),
    ( 23, 'SYN', 'Common syntax error', 'Date time field overflow'),
    ( 24, 'SYN', 'Common syntax error', 'Duplicate clause'),
    ( 25, 'SYN', 'Common syntax error', 'Using an undefined correlation name'),
    ( 26, 'SYN', 'Common syntax error', 'Too many columns in subquery'),
    ( 27, 'SYN', 'Common syntax error', 'Confusing table names with column names'),
    ( 28, 'SYN', 'Common syntax error', 'Restriction in SELECT clause (e.g., SELECT fee > 10)'),
    ( 29, 'SYN', 'Common syntax error', 'Projection in WHERE clause (e.g., WHERE firstname, surname)'),
    ( 30, 'SYN', 'Common syntax error', 'Confusing the order of keywords (e.g., FROM customer SELECT fee)'),
    ( 31, 'SYN', 'Common syntax error', 'Confusing the logic of keywords (e.g., grouping instead of ordering)'),
    ( 32, 'SYN', 'Common syntax error', 'Confusing the syntax of keywords (e.g., LIKE (''A'', ''B''))'),
    ( 33, 'SYN', 'Common syntax error', 'Omitting commas'),
    ( 34, 'SYN', 'Common syntax error', 'Curly, square or unmatched brackets'),
    ( 35, 'SYN', 'Common syntax error', 'IS where not applicable'),
    ( 36, 'SYN', 'Common syntax error', 'Nonstandard keywords or standard keywords in wrong context'),
    ( 37, 'SYN', 'Common syntax error', 'Nonstandard operators (e.g., &&, || or ==)'),
    ( 38, 'SYN', 'Common syntax error', 'Additional semicolon'),
    ( 39, 'SEM', 'Inconsistent expression', 'AND instead of OR (empty result table)'),
    ( 40, 'SEM', 'Inconsistent expression', 'Implied, tautological or inconsistent expression'),
    ( 41, 'SEM', 'Inconsistent expression', 'DISTINCT in SUM or AVG'),
    ( 42, 'SEM', 'Inconsistent expression', 'DISTINCT that might remove important duplicates'),
    ( 43, 'SEM', 'Inconsistent expression', 'Wildcards without LIKE'),
    ( 44, 'SEM', 'Inconsistent expression', 'Incorrect wildcard: using _ instead of % or using, e.g., *'),
    ( 45, 'SEM', 'Inconsistent expression', 'Mixing a > 0 with IS NOT NULL or empty string with NULL'),
    ( 46, 'SEM', 'Inconsistent join', 'NULL in IN/ANY/ALL subquery'),
    ( 47, 'SEM', 'Inconsistent join', 'Join on incorrect column (matches impossible)'),
    ( 48, 'SEM', 'Missing join', 'Omitting a join'),
    ( 49, 'SEM', 'Duplicate rows', 'Many duplicates'),
    ( 50, 'SEM', 'Redundant column output', 'Constant column output'),
    ( 51, 'SEM', 'Redundant column output', 'Duplicate column output'),
    ( 52, 'LOG', 'Operator error', 'OR instead of AND'),
    ( 53, 'LOG', 'Operator error', 'Extraneous NOT operator'),
    ( 54, 'LOG', 'Operator error', 'Missing NOT operator'),
    ( 55, 'LOG', 'Operator error', 'Substituting existence negation with <>'),
    ( 56, 'LOG', 'Operator error', 'Putting NOT in front of incorrect IN/EXISTS'),
    ( 57, 'LOG', 'Operator error', 'Incorrect comparison operator or incorrect value compared'),
    ( 58, 'LOG', 'Join error', 'Join on incorrect table'),
    ( 59, 'LOG', 'Join error', 'Join when join needs to be omitted'),
    ( 60, 'LOG', 'Join error', 'Join on incorrect column (matches possible)'),
    ( 61, 'LOG', 'Join error', 'Join with incorrect comparison operator'),
    ( 62, 'LOG', 'Join error', 'Missing join'),
    ( 63, 'LOG', 'Nesting error', 'Improper nesting of expressions'),
    ( 64, 'LOG', 'Nesting error', 'Improper nesting of subqueries'),
    ( 65, 'LOG', 'Expression error', 'Extraneous quotes'),
    ( 66, 'LOG', 'Expression error', 'Missing expression'),
    ( 67, 'LOG', 'Expression error', 'Expression on incorrect column'),
    ( 68, 'LOG', 'Expression error', 'Extraneous expression'),
    ( 69, 'LOG', 'Expression error', 'Expression in incorrect clause'),
    ( 70, 'LOG', 'Projection error', 'Extraneous column in SELECT'),
    ( 71, 'LOG', 'Projection error', 'Missing column from SELECT'),
    ( 72, 'LOG', 'Projection error', 'Missing DISTINCT from SELECT'),
    ( 73, 'LOG', 'Projection error', 'Missing AS from SELECT'),
    ( 74, 'LOG', 'Projection error', 'Missing column from ORDER BY clause'),
    ( 75, 'LOG', 'Projection error', 'Incorrect column in ORDER BY clause'),
    ( 76, 'LOG', 'Projection error', 'Extraneous ORDER BY clause'),
    ( 77, 'LOG', 'Projection error', 'Incorrect ordering of rows'),
    ( 78, 'LOG', 'Function error', 'DISTINCT as function parameter where not applicable'),
    ( 79, 'LOG', 'Function error', 'Missing DISTINCT from function parameter'),
    ( 80, 'LOG', 'Function error', 'Incorrect function'),
    ( 81, 'LOG', 'Function error', 'Incorrect column as function parameter'),
    ( 82, 'COM', 'Complication', 'Unnecessary complication'),
    ( 83, 'COM', 'Complication', 'Unnecessary DISTINCT in SELECT clause'),
    ( 84, 'COM', 'Complication', 'Unnecessary join'),
    ( 85, 'COM', 'Complication', 'Unused correlation name'),
    ( 86, 'COM', 'Complication', 'Correlation names are always identical'),
    ( 87, 'COM', 'Complication', 'Unnecessarily general comparison operator'),
    ( 88, 'COM', 'Complication', 'LIKE without wildcards'),
    ( 89, 'COM', 'Complication', 'Unnecessarily complicated SELECT in EXISTS subquery'),
    ( 90, 'COM', 'Complication', 'IN/EXISTS can be replaced by comparison'),
    ( 91, 'COM', 'Complication', 'Unnecessary aggregate function'),
    ( 92, 'COM', 'Complication', 'Unnecessary DISTINCT in aggregate function'),
    ( 93, 'COM', 'Complication', 'Unnecessary argument of COUNT'),
    ( 94, 'COM', 'Complication', 'Unnecessary GROUP BY in EXISTS subquery'),
    ( 95, 'COM', 'Complication', 'GROUP BY with singleton groups'),
    ( 96, 'COM', 'Complication', 'GROUP BY can be replaced with DISTINCT'),
    ( 97, 'COM', 'Complication', 'UNION can be replaced by OR'),
    ( 99, 'COM', 'Complication', 'Unnecessary column in ORDER BY clause'),
    (100, 'COM', 'Complication', 'ORDER BY in subquery'),
    (101, 'COM', 'Complication', 'Inefficient HAVING'),
    (102, 'COM', 'Complication', 'Inefficient UNION'),
    (103, 'COM', 'Complication', 'Condition in the subquery can be moved up'),
    (104, 'COM', 'Complication', 'Condition on left table in LEFT OUTER JOIN'),
    (105, 'COM', 'Complication', 'OUTER JOIN can be replaced by INNER JOIN')
    
    ON CONFLICT (id) DO NOTHING;

COMMIT;